//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public int id_asistencia { get; set; }
        public Nullable<int> id_clase { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string estado { get; set; }
    
        public virtual Clases Clases { get; set; }
    }
}
