//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public int id_asistencia { get; set; }
        public Nullable<int> id_estudiante { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string estado { get; set; }
        public Nullable<int> id_clase { get; set; }
    
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual Estudiantes Estudiantes1 { get; set; }
        public virtual Clases Clases { get; set; }
    }
}
