//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora_Movimientos
    {
        public int id_movimiento { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string accion { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string modulo { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
