//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora_Movimientos
    {
        public int id_movimiento { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string accion { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string modulo { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
