//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora_Accesos
    {
        public int id_acceso { get; set; }
        public int id_usuario { get; set; }
        public Nullable<System.DateTime> fecha_acceso { get; set; }
        public string tipo_acceso { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
