//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        public int id_horario { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_materia { get; set; }
        public string dia { get; set; }
        public Nullable<System.TimeSpan> hora_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_fin { get; set; }
    
        public virtual Materias Materias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
