//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        public int id_horario { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_materia { get; set; }
        public string dia { get; set; }
        public Nullable<System.TimeSpan> hora_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_fin { get; set; }
    
        public virtual Materias Materias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
