//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas
    {
        public int id_nota { get; set; }
        public Nullable<int> id_clase { get; set; }
        public Nullable<decimal> primer_examen { get; set; }
        public Nullable<decimal> segundo_examen { get; set; }
        public Nullable<decimal> tareas { get; set; }
        public Nullable<decimal> asistencia { get; set; }
        public Nullable<decimal> cotidiano { get; set; }
        public Nullable<decimal> nota_final { get; set; }
        public int id_estudiante { get; set; }
        public string periodo { get; set; }
    
        public virtual Clases Clases { get; set; }
        public virtual Clases Clases1 { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
    }
}
