//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistroDocenteEntities : DbContext
    {
        public RegistroDocenteEntities()
            : base("name=RegistroDocenteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asistencia> Asistencia { get; set; }
        public virtual DbSet<Bitacora_Accesos> Bitacora_Accesos { get; set; }
        public virtual DbSet<Bitacora_Movimientos> Bitacora_Movimientos { get; set; }
        public virtual DbSet<Calendario> Calendario { get; set; }
        public virtual DbSet<Clases> Clases { get; set; }
        public virtual DbSet<Estudiantes> Estudiantes { get; set; }
        public virtual DbSet<Horarios> Horarios { get; set; }
        public virtual DbSet<Materias> Materias { get; set; }
        public virtual DbSet<Notas> Notas { get; set; }
        public virtual DbSet<Reportes> Reportes { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Secciones> Secciones { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
